// VIBE service worker. Generated by build.py; do not edit by hand.
const VERSION = 'f1f2895d46d4';
const SHELL = 'vibe-shell-' + VERSION, ASSETS = 'vibe-assets-v1';
const PRECACHE = ['./', 'manifest.webmanifest', 'icons/icon-192.png', 'icons/icon-512.png', 'models/anims.glb', 'models/man.glb', 'models/woman.glb'];
self.addEventListener('install', e => {
  e.waitUntil(caches.open(SHELL).then(c => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith('vibe-shell-') && k !== SHELL).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
const isAsset = u => u.origin === location.origin ? /\/(models|icons)\//.test(u.pathname)
  : /^(cdn\.jsdelivr\.net|cdnjs\.cloudflare\.com|fonts\.googleapis\.com|fonts\.gstatic\.com)$/.test(u.hostname);
self.addEventListener('fetch', e => {
  const req = e.request; if (req.method !== 'GET') return;
  const u = new URL(req.url);
  if (req.mode === 'navigate' || (u.origin === location.origin && /\/(index\.html)?$/.test(u.pathname))) {
    e.respondWith(fetch(req).then(r => { const c = r.clone(); caches.open(SHELL).then(s => s.put('./', c)); return r; })
      .catch(() => caches.match('./').then(r => r || Response.error())));
    return;
  }
  if (!isAsset(u)) return;   // Supabase and everything else: straight to the network
  e.respondWith(caches.open(ASSETS).then(async c => {
    const hit = await c.match(req);
    const net = fetch(req).then(r => { if (r.ok || r.type === 'opaque') c.put(req, r.clone()); return r; }).catch(() => hit || Response.error());
    return hit || net;
  }));
});
